Repository Pseudo-Lab/data-engineering-for-everybody, pull requests merged in 2023-07, with the labels that each got.

#48 UPDATE Readme, intro.md
  README.md
  book/_toc.yml
  book/docs/0_checklist/list.md
  book/docs/8_cloud_computing_and_data_engineering/8.1_cloud_computing.md
  book/docs/8_cloud_computing_and_data_engineering/8.2_data_engineering.md
  book/docs/8_cloud_computing_and_data_engineering/8.3_cloud_computing_data_engineering.md
  book/docs/8_cloud_computing_and_data_engineering/8.4_use_case_cloud_dataengineering.md
  book/docs/8_cloud_computing_and_data_engineering/8.5_multi_cloud_dataengineering.md
  book/docs/8_cloud_computing_and_data_engineering/images/1.1.png
  book/docs/8_cloud_computing_and_data_engineering/images/1.2.png
  book/docs/8_cloud_computing_and_data_engineering/images/1.3.png
  book/docs/8_cloud_computing_and_data_engineering/images/1.4.png
  book/docs/8_cloud_computing_and_data_engineering/images/1.5.png
  book/docs/8_cloud_computing_and_data_engineering/images/1.6.png
  book/docs/8_cloud_computing_and_data_engineering/images/1.7.png
  book/docs/8_cloud_computing_and_data_engineering/images/1.8.png
  book/docs/8_cloud_computing_and_data_engineering/images/1.9.png
  book/docs/8_cloud_computing_and_data_engineering/images/2.1.png
  book/docs/8_cloud_computing_and_data_engineering/images/2.2.png
  book/docs/8_cloud_computing_and_data_engineering/images/2.3.png
  book/docs/8_cloud_computing_and_data_engineering/images/2.4.png
  book/docs/8_cloud_computing_and_data_engineering/images/2.5.png
  book/docs/8_cloud_computing_and_data_engineering/images/2.6.png
  book/docs/8_cloud_computing_and_data_engineering/images/3.1.png
  book/docs/8_cloud_computing_and_data_engineering/images/3.2.png
  book/docs/8_cloud_computing_and_data_engineering/images/3.3.png
  book/docs/8_cloud_computing_and_data_engineering/images/3.4.png
  book/docs/8_cloud_computing_and_data_engineering/images/3.5.png
  book/docs/8_cloud_computing_and_data_engineering/images/9.3.1_architecture_dbt.png
  book/docs/8_cloud_computing_and_data_engineering/images/9.3.1_example_apache_superset.png
  book/docs/8_cloud_computing_and_data_engineering/images/9.3.1_example_elt_pipeline_with_dbt.png
  book/docs/8_cloud_computing_and_data_engineering/images/9.3.3_gcp_recommend_pipeline.png
  book/docs/8_cloud_computing_and_data_engineering/images/9.4_multi_cloud_pipeline_detail.png
  book/docs/8_cloud_computing_and_data_engineering/images/9.4_multi_cloud_pipeline_overview.png
  book/docs/8_cloud_computing_and_data_engineering/images/9.4_multicloud_applied.png
  book/docs/8_cloud_computing_and_data_engineering/images/9.4_multicloud_consideration.png
  book/docs/8_cloud_computing_and_data_engineering/images/9.5_explain_pub_sub.png
  book/docs/8_cloud_computing_and_data_engineering/images/Untitled 9.png
  book/docs/8_cloud_computing_and_data_engineering/images/___.png
  book/docs/8_cloud_computing_and_data_engineering/images/appendix_cloud_services.png
  book/docs/8_cloud_computing_and_data_engineering/images/appendix_example_rental_car_onpremise_cloud.png
  book/docs/8_cloud_computing_and_data_engineering/images/appendix_hybrid_computing.png
  book/docs/8_cloud_computing_and_data_engineering/images/appendix_onpremise_cloud.png
  book/docs/8_cloud_computing_and_data_engineering/images/other_way.png
  book/docs/8_cloud_computing_and_data_engineering/main_page.md
  book/docs/8_cloud_computing_and_data_engineering/reference.md
  book/docs/8_introduction_to_apache_airflow/template_main_page.md
  book/docs/8_introduction_to_apache_airflow/template_sub_page.md
  book/docs/9_cloud_computing_and_data_engineering/1_cloud_computing.md
  book/intro.md
Labels: 📑 docs

#46 Migration subpage6 to subpage1,3
  book/docs/2_data_source_and_data_collection/images/sub_page3_3.png
  book/docs/2_data_source_and_data_collection/template_sub_page1.md
  book/docs/2_data_source_and_data_collection/template_sub_page3.md
  template_sub_page6.md
Labels: 📝 session

#51 [session-4.2] Fix deploy issue & Change tone
  book/_toc.yml
  book/docs/1_introduction_to_data_engineering/1.4_further_more.md
  book/docs/1_introduction_to_data_engineering/1_introduction_to_data_engineering.md
  book/docs/4_data_storage/2.1_key_value_store.md
  book/docs/4_data_storage/2.2_wide_column_store.md
  book/docs/4_data_storage/2.3_document_store.md
  book/docs/4_data_storage/2.4_graph_store.md
  book/docs/4_data_storage/3_references.md
  book/docs/4_data_storage/4.2.1_key_value_store.md
  book/docs/4_data_storage/4.2.2_wide_column_store.md
  book/docs/4_data_storage/4.2.3_document_store.md
  book/docs/4_data_storage/4.2.4_graph_store.md
  book/docs/4_data_storage/4.2_databases.md
  book/docs/4_data_storage/4.3_references.md
  book/docs/4_data_storage/images/2.1_kvs_data_types.png
  book/docs/4_data_storage/images/2.1_kvs_value_properties.png
  book/docs/4_data_storage/images/2.2_wide_column_detail.png
  book/docs/4_data_storage/images/2.4_graph_query.png
  book/docs/4_data_storage/images/4.2.1_kvs_rank.png
  book/docs/4_data_storage/images/4.2.2_wide_column.png
  book/docs/4_data_storage/images/4.2.2_wide_column_rank.png
  book/docs/4_data_storage/images/4.2.3_document_db.png
  book/docs/4_data_storage/images/4.2.3_document_db_rank.png
  book/docs/4_data_storage/images/4.2.3_sharding.png
  book/docs/4_data_storage/images/4.2.4_graph_rank.png
  book/docs/4_data_storage/images/4.2.4_graph_structure.png
  book/docs/4_data_storage/images/4.2.4_neo4j.png
  book/docs/4_data_storage/images/4.2.4_neo4j_example.png
Labels: 📝 session

#47 Upload Session6-1 & Change tone
  book/_toc.yml
  book/docs/6_data_processing_frameworks_2/1._Stream_processing_Framework.md
  book/docs/6_data_processing_frameworks_2/2.0_Apache-spark.md
  book/docs/6_data_processing_frameworks_2/2.1_Apache-spark_pratice.ipynb
  book/docs/6_data_processing_frameworks_2/3._Apache-kafka.md
  book/docs/6_data_processing_frameworks_2/4._Apache-storm.md
  book/docs/6_data_processing_frameworks_2/5._Apache-flink.md
  book/docs/6_data_processing_frameworks_2/images/1.1_streamprocessing.png
  book/docs/6_data_processing_frameworks_2/images/1.2_eventprocessing.png
  book/docs/6_data_processing_frameworks_2/images/2.1_sparckstructure.png
  book/docs/6_data_processing_frameworks_2/images/2.2_speedcomparision.png
  book/docs/6_data_processing_frameworks_2/images/2.3_sparckclusterinfra.png
  book/docs/6_data_processing_frameworks_2/images/2.4_clusterspattern.png
  book/docs/6_data_processing_frameworks_2/images/2.5_sparkjvm.png
  book/docs/6_data_processing_frameworks_2/images/2.6_rddlineage.png
  book/docs/6_data_processing_frameworks_2/images/2.7_sparksession.png
  book/docs/6_data_processing_frameworks_2/images/2.8_dag.png
Labels: 📝 session

#54 UPDATE README.md and UPDATE intro.md
  README.md
  book/intro.md
Labels: 🐌 bug

#34 데이터 처리 프레임워크(1) 업데이트
  book/_toc.yml
  book/docs/5_data_processing_frameworks_1/2.3_map_reduce.md
  book/docs/5_data_processing_frameworks_1/5.1.1_big_data.md
  book/docs/5_data_processing_frameworks_1/5.1.2_parallel_and_distribution.md
  book/docs/5_data_processing_frameworks_1/5.1.3_cache.md
  book/docs/5_data_processing_frameworks_1/5.1.4_indexing.md
  book/docs/5_data_processing_frameworks_1/5.1.5_memory_optimization.md
  book/docs/5_data_processing_frameworks_1/5.1.6_in_memory_db.md
  book/docs/5_data_processing_frameworks_1/5.1.7_distribution_system.md
  book/docs/5_data_processing_frameworks_1/5.1_data_processing_basic.md
  book/docs/5_data_processing_frameworks_1/5.2.1_hadoop_ecosystem.md
  book/docs/5_data_processing_frameworks_1/5.2.2_hdfs.md
  book/docs/5_data_processing_frameworks_1/5.2.3_map_reduce.md
  book/docs/5_data_processing_frameworks_1/5.2.4_map_reduce_example.md
  book/docs/5_data_processing_frameworks_1/5.2_hadoop.md
  book/docs/5_data_processing_frameworks_1/5.3_reference.md
Labels: 📝 session

#58 github id 누락 추가
  README.md
  book/intro.md
Labels: 📑 docs

#57 [session-7] introduction to apache airflow
  book/_toc.yml
  book/docs/7_introduction_to_apache_airflow/7.1_airflow_theory.md
  book/docs/7_introduction_to_apache_airflow/7.2_airflow_executor.md
  book/docs/7_introduction_to_apache_airflow/7.3_airflow_use_cases.md
  book/docs/7_introduction_to_apache_airflow/7.4.1_airflow_hands_on.ipynb
  book/docs/7_introduction_to_apache_airflow/7.4_airflow_hands_on.md
  book/docs/7_introduction_to_apache_airflow/7.5_reference.md
  book/docs/7_introduction_to_apache_airflow/images/7_1_1.png
  book/docs/7_introduction_to_apache_airflow/images/7_1_2.png
  book/docs/7_introduction_to_apache_airflow/images/7_2_1.png
  book/docs/7_introduction_to_apache_airflow/images/7_2_2.png
  book/docs/7_introduction_to_apache_airflow/images/7_2_3.png
  book/docs/7_introduction_to_apache_airflow/images/7_2_4.png
  book/docs/7_introduction_to_apache_airflow/images/7_2_5.png
  book/docs/7_introduction_to_apache_airflow/images/7_3_1.png
  book/docs/7_introduction_to_apache_airflow/images/7_4_1.png
  book/docs/7_introduction_to_apache_airflow/images/7_4_2.png
  book/docs/7_introduction_to_apache_airflow/main_page.md
  book/docs/8_introduction_to_apache_airflow/template_main_page.md
  book/docs/8_introduction_to_apache_airflow/template_sub_page.md
Labels: 📝 session
